In [27]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://davidgrisales:password@localhost:5432/qversity')
def query(sql_query):
    return pd.read_sql_query(sql_query, engine)

In [ ]:
query("select count(risk_score) from silver.stg_customers where risk_score is not")

   count
0   5000

In [39]:
query("select distinct customer_segment, count(*) from silver.stg_customers group by customer_segment")

   customer_segment  count
0     banca_privada     55
1         minorista     68
2           premium   1049
3           Premium     94
4           PREMIUM     87
5   private_banking   1033
6   Private_Banking     73
7   PRIVATE_BANKING     63
8              pyme     50
9              PYME     57
10           retail   1084
11           Retail     66
12           RETAIL     62
13              sme   1050
14              Sme     56
15              SME     53

# Customer Segment Normalization

The `customer_segment` field is expected to contain the following standardized values:

- `retail`
- `premium`
- `private_banking`
- `sme`

However, some records include Spanish variants that need to be translated and normalized as follows:

| Original Value | Standardized Value |
|----------------|---------------------|
| `banca_privada` | `private_banking`   |
| `minorista`     | `retail`            |
| `pyme`          | `sme`               |

> **Note:** `pyme` stands for *pequeña y mediana empresa* (small and medium enterprise).

Additionally, all values in the `customer_segment` field should be converted to lowercase to ensure consistency and support downstream processing and analysis.

In [38]:
query("select count(*) from silver.stg_customers where customer_segment like 'pyme' or customer_segment like 'PYME'")

   count
0    107

In [54]:
query("select distinct relationship_manager from silver.stg_customers")

   relationship_manager
0                  None
1      Sebastian Castro
2      Valentina Torres
3                    NA
4        Luis Hernandez
5           Sofia Lopez
6         Diego Ramirez
7         Daniela Rojas
8       Isabella Vargas
9          Lucia Ortega
10         Maria Garcia
11         Camila Reyes
12       Alejandro Diaz
13         Ana Martinez
14
15       Andres Morales
16                 null
17     Carlos Rodriguez
18      Nicolas Mendoza
19                  N/A

# Relationship Manager Normalization

The `relationship_manager` field contains null values represented in various ways, including:

- `N/A`
- `null`
- `None`
- Empty spaces

All such values must be normalized to **`null`** (or `NULL`) in cases where no relationship manager has been assigned. This ensures consistency and enables accurate downstream processing and analysis.

In [56]:
query("select distinct status from silver.stg_customers")

        status
0     inactive
1       ACTIVE
2     inactivo
3       ACTIVO
4       CLOSED
5      Cerrado
6       Active
7       activo
8       Activo
9    Suspended
10   suspended
11      active
12      closed
13    INACTIVE
14    Inactivo
15      Closed
16   SUSPENDED
17  suspendido
18     cerrado
19    Inactive

# Status Normalization

Similar to the `customer_segment` field, the `status` field contains values that are not consistently lowercase or are written in Spanish instead of English.

The expected standardized values are:

- `active`
- `inactive`
- `suspended`
- `closed`

The following Spanish variants must be translated and normalized:

| Original Value | Standardized Value |
|----------------|---------------------|
| `activo`       | `active`            |
| `inactivo`     | `inactive`          |
| `suspendido`   | `suspended`         |
| `cerrado`      | `closed`            |

Additionally, all values in the `status` field should be converted to **lowercase** to ensure consistency and support downstream processing and analysis.

# Accounts EDA

In [80]:
import pandas as pd
accounts_df = pd.read_sql_table('stg_accounts', con=engine , schema='silver')
accounts_df.head()

,customer_id,account_id,status,balance,currency,branch_code,opened_date,account_type,credit_limit,interest_rate
0,CUST-0000001,ACC-7B841C599005,active,294632.84,USD,BR-320,2021-01-14,checking,NaN,20.33
1,CUST-0000001,ACC-385664AAA258,closed,171579.81,PEN,BR-487,2022-01-23,investment,NaN,2.87
2,CUST-0000001,ACC-94B1E2D62CFF,closed,414702.33,USD,BR-181,03-01-2024,savings,NaN,15.65
3,CUST-0000001,ACC-DAA30BD045F9,cerrado,703233.52,PEN,BR-763,2021-12-15,checking,NaN,11.61
4,CUST-0000001,ACC-DE7103A41227,closed,988158.77,PEN,BR-801,2023-03-01,savings,NaN,6.50

In [82]:
accounts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17529 entries, 0 to 17528
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    17529 non-null  object
 1   account_id     17529 non-null  object
 2   status         17529 non-null  object
 3   balance        17043 non-null  float64
 4   currency       17529 non-null  object
 5   branch_code    17529 non-null  object
 6   opened_date    17529 non-null  object
 7   account_type   17529 non-null  object
 8   credit_limit   4461 non-null   float64
 9   interest_rate  17529 non-null  float64
dtypes: float64(3), object(7)
memory usage: 1.3+ MB

In [83]:
null_counts = accounts_df.isnull().sum()
print(null_counts)

customer_id          0
account_id           0
status               0
balance            486
currency             0
branch_code          0
opened_date          0
account_type         0
credit_limit     13068
interest_rate        0
dtype: int64

In [61]:
query("select distinct account_type from silver.stg_accounts limit 10;")

      account_type
0         savings
1    credit_card
2      credit_card
3    credit_card
4       checking
5         checking
6          savings
7       checking
8      investment
9     investment

# Account Type Normalization

The required normalization for the `account_type` field consists of:

1. **Trim whitespace** – Remove any leading or trailing spaces
2. **Convert to lowercase** – Ensure all values are uniformly lowercase

However, exploratory data analysis (EDA) confirms that this transformation is **not necessary**, as all values are already in lowercase.

In [63]:
query("SELECT distinct currency FROM silver.stg_accounts LIMIT 10;")

  currency
0      COP
1      ARS
2      UYU
3      MXN
4      PEN
5      BRL
6      CLP
7      USD

## Currency Normalization

No changes are required for the `currency` field. All values are already aligned with the expected constraints. Uppercase formatting is standard and acceptable for this field.

## Balance

In [113]:
query("select min(balance), max(balance) from silver.stg_accounts;")

      min           max
0  237.85  1.999231e+09

In [119]:
query("select * from silver.stg_accounts where balance is null limit 10;")

,customer_id,account_id,status,balance,currency,branch_code,opened_date,account_type,credit_limit,interest_rate
0,CUST-0000018,ACC-6EA2141F2ACE,closed,None,MXN,BR-843,03-19-2022,checking,NaN,8.15
1,CUST-0000021,ACC-39B99DD4C68D,FROZEN,None,COP,BR-884,2026-03-25,credit_card,71491473.07,23.63
2,CUST-0000037,ACC-EFD4AF498112,active,None,USD,BR-868,2021-04-20,savings,NaN,7.84
3,CUST-0000039,ACC-E2C4DB72051C,active,None,UYU,BR-321,2026-01-27,checking,NaN,7.29
4,CUST-0000058,ACC-49980AE4FC6B,active,None,USD,BR-346,2026-04-13,credit_card,46523.37,21.02
5,CUST-0000068,ACC-2ADA981BAF35,active,None,USD,BR-985,2025-03-21,credit_card,4393.21,12.24
6,CUST-0000069,ACC-3D8D7D7AE02A,frozen,None,USD,BR-566,2024-05-14,investment,NaN,11.95
7,CUST-0000070,ACC-697BFD0B7869,frozen,None,USD,BR-174,08-02-2021,checking,NaN,10.61
8,CUST-0000077,ACC-8AD2C23AC33C,closed,None,USD,BR-865,2025-06-19,checking,NaN,9.43
9,CUST-0000087,ACC-B4763072C3FD,Closed,None,USD,BR-230,2024-08-01,savings,NaN,17.68

In [120]:
query("select * from silver.stg_accounts where balance is not null limit 10;")

,customer_id,account_id,status,balance,currency,branch_code,opened_date,account_type,credit_limit,interest_rate
0,CUST-0000001,ACC-7B841C599005,active,2.946328e+05,USD,BR-320,2021-01-14,checking,NaN,20.33
1,CUST-0000001,ACC-385664AAA258,closed,1.715798e+05,PEN,BR-487,2022-01-23,investment,NaN,2.87
2,CUST-0000001,ACC-94B1E2D62CFF,closed,4.147023e+05,USD,BR-181,03-01-2024,savings,NaN,15.65
3,CUST-0000001,ACC-DAA30BD045F9,cerrado,7.032335e+05,PEN,BR-763,2021-12-15,checking,NaN,11.61
4,CUST-0000001,ACC-DE7103A41227,closed,9.881588e+05,PEN,BR-801,2023-03-01,savings,NaN,6.50
5,CUST-0000002,ACC-3F3F63EE6C0B,closed,1.728436e+05,USD,BR-360,2025-09-11,savings,NaN,19.77
6,CUST-0000002,ACC-A7D4F2BC48B7,frozen,8.456400e+02,USD,BR-171,20240205,savings,NaN,23.18
7,CUST-0000003,ACC-E8A50B6E5699,closed,4.726178e+05,USD,BR-303,2025-01-04,savings,NaN,24.70
8,CUST-0000003,ACC-B879137EBCAE,closed,5.332663e+04,USD,BR-381,2025-01-21,credit_card,38755.07,9.29
9,CUST-0000003,ACC-F6795B501588,closed,4.325431e+08,CLP,BR-735,01/10/2025,savings,NaN,18.76

No transformation is required here.

In [124]:
query("select type, currency, sum(amount) as total_amount from silver.stg_transactions where account_id='ACC-6EA2141F2ACE' group by type, currency")

       type currency  total_amount
0   deposit      MXN           NaN
1       fee      MXN     843786.61
2       FEE      MXN     426029.49
3   payment      MXN     459612.45
4    refund      MXN    1488640.84
5  transfer      MXN     461114.93

In [125]:
query("select type, currency, amount from silver.stg_transactions where account_id='ACC-6EA2141F2ACE' and type='deposit' and currency='MXN';")

      type currency amount
0  deposit      MXN   None

## Credit Limit

In [65]:
query("select min(credit_limit), max(credit_limit) from silver.stg_accounts;")

       min           max
0  1053.72  3.981051e+08

In [ ]:
query("select count(*) from silver.stg_accounts where credit_limit is null;")

   count
0  13068

In [112]:
query("select trim(account_type) new_account_type, count(*) from silver.stg_accounts  where credit_limit is not null group by new_account_type;")

  new_account_type  count
0      credit_card   4461

No transformation is required here.

## Interest rate

In [68]:
query("select currency, min(interest_rate), max(interest_rate) from silver.stg_accounts group by currency;")

  currency   min    max
0      COP  0.52  25.00
1      ARS  0.53  25.00
2      UYU  0.51  24.98
3      MXN  0.55  25.00
4      PEN  0.51  24.99
5      BRL  0.51  24.91
6      CLP  0.50  25.00
7      USD  0.50  24.99

In [ ]:
No changes are required here.

## Opened Date

In [69]:
query("select opened_date from silver.stg_accounts limit 10;")

  opened_date
0  2021-01-14
1  2022-01-23
2  03-01-2024
3  2021-12-15
4  2023-03-01
5  2025-09-11
6    20240205
7  2025-01-04
8  2025-01-21
9  01/10/2025

In [75]:
query("SELECT count(*) from silver.stg_accounts where opened_date is null;")

   count
0      0

We have to normalize the format of opened_date, which follow these patterns:
- mm-dd-yyyy
- yyyy-mm-dd
- dd/mm/yyyy
Ideally it must be normalized to yyyy-mm-dd

In [ ]:
query("select distinct status from silver.stg_accounts;")

       status
0      ACTIVE
1      active
2      closed
3   congelado
4      Closed
5      Frozen
6      CLOSED
7      FROZEN
8      Active
9      activo
10    cerrado
11     frozen

In [73]:
query("select count(*) from silver.stg_customers where customer_segment is null")

   count
0      0

# Account Status Normalization

The `account_status` field has three possible standardized values:

- `active`
- `closed`
- `frozen`

All values must be converted to **lowercase**. Additionally, the following Spanish variants must be translated and normalized:

| Original Value | Standardized Value |
|----------------|---------------------|
| `activo`       | `active`            |
| `cerrado`      | `closed`            |
| `congelado`    | `frozen`            |